### ISSUE TITLE
Not able to use this package

### ISSUE THREAD

**Issue by sudo-pradip** [woudw/dbt-synapse-spark#1]
## Issue
- I have install and setup this package with azure synapse spark, i able to submit the job and query to azure synapse, but i getting below errors when i run
 
- `dbt run` : 
```
     
== SQL ==
/* {"app": "dbt", "dbt_version": "1.3.7", "profile_name": "sy_spark", "target_name": "dev", "connection_name": "create__"} */
create schema if not exists 
  
--^^^

org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:306)org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:143)org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:52)org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:89)io.delta.sql.parser.DeltaSqlParser.$anonfun$parsePlan$1(DeltaSqlParser.scala:78)io.delta.sql.parser.DeltaSqlParser.parse(DeltaSqlParser.scala:111)io.delta.sql.parser.DeltaSqlParser.parsePlan(DeltaSqlParser.scala:75)com.microsoft.azure.synapse.ml.predict.SynapsePredictParser.parsePlan(SynapsePredictParser.scala:19)org.apache.spark.sql.SparkSession.$anonfun$sql$2(SparkSession.scala:620)org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:120)org.apache.spark.sql.SparkSession.$anonfun$sql$1(SparkSession.scala:620)org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)org.apache.spark.sql.SparkSession.sql(SparkSession.scala:617)org.apache.livy.repl.SQLInterpreter.execute(SQLInterpreter.scala:129)org.apache.livy.repl.Session.$anonfun$executeCode$1(Session.scala:721)scala.Option.map(Option.scala:230)org.apache.livy.repl.Session.executeCode(Session.scala:718)org.apache.livy.repl.Session.$anonfun$execute$4(Session.scala:492)org.apache.livy.repl.Session.withRealtimeOutputSupport(Session.scala:941)org.apache.livy.repl.Session.$anonfun$execute$1(Session.scala:492)scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)scala.util.Success.$anonfun$map$1(Try.scala:255)scala.util.Success.map(Try.scala:213)scala.concurrent.Future.$anonfun$map$1(Future.scala:292)scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:750)
```
- `dbt debug`
```
1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:

  >'SynapseSparkConnectionManager' object has no attribute 'handle'

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile
```

## Environment 
- Ubuntu 22
- dbt core 1.3.7

## How i install
- `pip3 install git+https://github.com/woudw/dbt-synapse-spark`
- configure dbt profile + az login

## Note
- If i stop session from azure synapse studio, then i can't reuse same session, meaning that `dbt run` will not work after i stop session manually, is expected ?

Thanks for this package :heart:

**Comment by woudw** [comment]
HI! Thanks for this issue.
I haven't maintained this package for a while, and 'Not able to use this package' seems like a good first issue :)

Can you share your profile? Maybe I can take a look, or reproduce this issue.

**Comment by sudo-pradip** [comment]
Hi @woudw 
thanks for replay :stars: ,
here is profile 

```
az_sy_spark_proj:
  outputs:
    dev:
      authentication2: AzureCliCredential
      authentication: DefaultAzureCredential
      cluster_configuration:
        driver_cores: 1
        driver_memory: 1g
        executor_cores: 1
        executor_memory: 1g
        num_executors: 1
      poll_interval: 2
      spark_pool: dbtsynapsespark
      threads: 1
      type: synapsespark
      user: pradip.session
      workspace: dbt-synapse-rnd-wp
      schema: default
      database: default
  target: dev
```
